# logfilename                               [owner:group]  mode count size(KB) when  flags
/var/log/dt-mac-agent/agent.log             root:wheel     640  3     1024     *     NJ
/var/log/dt-mac-agent/watchdog.log          root:wheel     640  3     1024     *     NJ
/var/log/dt-mac-agent/agent.stdout.log      root:wheel     640  2     512      *     NJ
/var/log/dt-mac-agent/agent.stderr.log      root:wheel     640  2     512      *     NJ
/var/log/dt-mac-agent/watchdog.stdout.log   root:wheel     640  2     512      *     NJ
/var/log/dt-mac-agent/watchdog.stderr.log   root:wheel     640  2     512      *     NJ
