# logfilename                                    [owner:group]  mode count size(KB) when  flags
/Library/Logs/dt-mac-agent/agent.log             root:wheel     644  5     1024     *     NJ
/Library/Logs/dt-mac-agent/ingest.log            root:wheel     644  5     2048     *     NJ
/Library/Logs/dt-mac-agent/watchdog.log          root:wheel     644  3     1024     *     NJ
/Library/Logs/dt-mac-agent/install.log           root:admin     640  3     512      *     NJ
/Library/Logs/dt-mac-agent/payloads.log          root:wheel     644  3     10240    *     NJ
/Library/Logs/dt-mac-agent/agent.stdout.log      root:wheel     644  2     512      *     NJ
/Library/Logs/dt-mac-agent/agent.stderr.log      root:wheel     644  2     512      *     NJ
/Library/Logs/dt-mac-agent/watchdog.stdout.log   root:wheel     644  2     512      *     NJ
/Library/Logs/dt-mac-agent/watchdog.stderr.log   root:wheel     644  2     512      *     NJ
